"""CLI interface for base-scanner."""

import argparse
import json
import sys

from .scanner import SecurityScanner


def format_report_markdown(result: dict) -> str:
    """Format scan results as markdown."""
    if "error" in result:
        return f"# Security Scan Failed\n\n**Address:** {result['address']}\n**Error:** {result['error']}\n"

    lines = [
        f"# Security Scan Report",
        f"",
        f"**Contract:** {result.get('contract_name', 'Unknown')} ({result['address']})",
        f"**Compiler:** {result.get('compiler', 'Unknown')}",
        f"**Chain ID:** {result.get('chain_id', 8453)}",
        f"**Scan Time:** {result['scan_time']}",
        f"",
        f"## Summary",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| 🔴 Critical | {result['summary']['critical']} |",
        f"| 🟠 High | {result['summary']['high']} |",
        f"| 🟡 Medium | {result['summary']['medium']} |",
        f"| 🔵 Low | {result['summary']['low']} |",
        f"| ⚪ Info | {result['summary']['info']} |",
        f"| **Total** | **{result['summary']['total']}** |",
        f"",
    ]

    if result["findings"]:
        lines.append("## Findings\n")
        for i, f in enumerate(result["findings"], 1):
            severity_emoji = {
                "CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪"
            }.get(f["severity"], "⚪")
            lines.append(f"### {i}. {severity_emoji} [{f['severity']}] {f['title']}")
            lines.append(f"**Category:** {f['category']}")
            lines.append(f"")
            lines.append(f"{f['description']}")
            if f.get("evidence"):
                lines.append(f"")
                lines.append(f"```")
                lines.append(f"{f['evidence']}")
                lines.append(f"```")
            lines.append(f"")
    else:
        lines.append("## Findings\n")
        lines.append("No issues found. This does not guarantee the contract is secure.")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by base-scanner*")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="base-scanner — Lightweight on-chain security scanner for Base contracts"
    )
    parser.add_argument("address", help="Contract address to scan")
    parser.add_argument("--chain-id", type=int, default=8453, help="Chain ID (default: 8453 for Base)")
    parser.add_argument("--output", "-o", help="Output file (default: stdout)")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    scanner = SecurityScanner(args.address, chain_id=args.chain_id)
    result = scanner.scan()

    if args.json:
        output = json.dumps(result, indent=2)
    else:
        output = format_report_markdown(result)

    if args.output:
        with open(args.output, "w") as f:
            f.write(output)
        print(f"[*] Report saved to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
